### ISSUE TITLE
/useitem doesn't work with HQ items

### ISSUE THREAD

**Issue by shelltar** [UnknownX7/OOBlugin#1]
As in title, /useitem works fine on NQ items, but when trying to use a HQ item, I'm getting "You do not have that item" error.

Edit: It doesn't work with item ID. It works with the item name, I was putting it in quotation marks before, that's why it didn't work.

**Comment by UnknownX7** [comment]
The interprets the normal ID + 1,000,000 as the HQ ID. (The HQ ID of 5678 is 1005678)
